scraping:
  platform: OpenReview
  conference: ICLR
  year: 2024
  track: Conference
  submission_type: tab-accept-oral
  delay: 2

paths:
  output_dir: data/downloaded_papers
  db_path: sqlite:///data/papers.db

summarization:
  provider: hf
  model_name: facebook/opt-350m
  prefix: "Summarize the following text:"
  suffix: "Summary:"
  param:
    max_new_tokens: 1000
    temperature: 0.7
