- name: CVPR2024Oral
  scraping:
    platform: cvpr
    filters:
      year: 2024
      filter_name: sessions
      filter_value: Oral
    # num_cap: 5
    enforce_rescrape: false
    cap_at: "References"
    delay: 1

  paths:
    output_dir: data/downloaded_papers/cvpr2024_oral
    db_path: sqlite:///data/cvpr2024_oral.db

  summarization:
    provider: openai
    model_name: gpt-4o-mini
    prefix: "Summarize the following academic paper, and output your summary in the following format: [Topics:] <five keywords describing the main topics of the paper, with commas separating them and relevance descending> [Summary:] <summary as one concise paragraph>"
    suffix: ""
    content_cap: null
    param:
      max_tokens: 1000
      temperature: 0.7
