- name: "CVPR 2024 Oral"
  scraping:
    platform: cvpr
    filters:
      year: 2024
      filter_name: sessions
      filter_value: Oral
    # num_cap: 5
    enforce_rescrape: false
    cap_at: "References"
    delay: 1

  paths:
    output_dir: data/downloaded_papers
    db_path: sqlite:///data/papers.db

  summarization:
    provider: openai
    model_name: gpt-4o-mini
    prefix: ""
    suffix: "Summarize the above academic paper and structure your response in the following format: [Topics:] <Provide five keywords that capture the primary themes or concepts of the paper, listed in descending order of relevance, separated by commas.> [TL;DR:] <Write one concise sentence that encapsulates the paper's main contribution or finding.> [Summary:] <Write one concise paragraph that provides a high-level overview of the paper, focusing on its objective, methods, results, and implications. Ensure your summary reflects the paper's content accurately, without adding interpretations or assumptions. Check your response for clarity, conciseness, and fidelity to the original text.>"
    content_cap: null
    param: {}