- name: NeurIPS2024Oral
  scraping:
    platform: OpenReview
    filters:
      conference: NeurIPS.cc
      year: 2024
      track: Conference
      submission_type: tab-accept-oral
    enforce_rescrape: true
    cap_at: "REFERENCES"
    delay: 1
  
  paths:
    output_dir: data/downloaded_papers/neurips2024_oral
    db_path: sqlite:///data/neurips2024_oral.db
  
  summarization:
    provider: openai
    model_name: gpt-4o-mini
    prefix: ""
    suffix: "Summarize the above academic paper and structure your response in the following format: [Topics:] <Provide five keywords that capture the primary themes or concepts of the paper, listed in descending order of relevance, separated by commas.> [TL;DR:] <Write one concise sentence that encapsulates the paper's main contribution or finding.> [Summary:] <Write one concise paragraph that provides a high-level overview of the paper, focusing on its objective, methods, results, and implications. Ensure your summary reflects the paper's content accurately, without adding interpretations or assumptions. Check your response for clarity, conciseness, and fidelity to the original text.>"
    content_cap: null
    param: {}
  
- name: ICML2024Oral
  scraping:
    platform: OpenReview
    filters:
      conference: ICML.cc
      year: 2024
      track: Conference
      submission_type: tab-accept-oral
    enforce_rescrape: true
    cap_at: "REFERENCES"
    delay: 1

  paths:
    output_dir: data/downloaded_papers/icml2024_oral
    db_path: sqlite:///data/icml2024_oral.db

  summarization:
    provider: openai
    model_name: gpt-4o-mini
    prefix: ""
    suffix: "Summarize the above academic paper and structure your response in the following format: [Topics:] <Provide five keywords that capture the primary themes or concepts of the paper, listed in descending order of relevance, separated by commas.> [TL;DR:] <Write one concise sentence that encapsulates the paper's main contribution or finding.> [Summary:] <Write one concise paragraph that provides a high-level overview of the paper, focusing on its objective, methods, results, and implications. Ensure your summary reflects the paper's content accurately, without adding interpretations or assumptions. Check your response for clarity, conciseness, and fidelity to the original text.>"
    content_cap: null
    param: {}

- name: ICLR2024Oral
  scraping:
    platform: OpenReview
    filters:
      conference: ICLR.cc
      year: 2024
      track: Conference
      submission_type: tab-accept-oral
    enforce_rescrape: true
    cap_at: "REFERENCES"
    delay: 1
  
  paths:
    output_dir: data/downloaded_papers/iclr2024_oral
    db_path: sqlite:///data/iclr2024_oral.db
  
  summarization:
    provider: openai
    model_name: gpt-4o-mini
    prefix: ""
    suffix: "Summarize the above academic paper and structure your response in the following format: [Topics:] <Provide five keywords that capture the primary themes or concepts of the paper, listed in descending order of relevance, separated by commas.> [TL;DR:] <Write one concise sentence that encapsulates the paper's main contribution or finding.> [Summary:] <Write one concise paragraph that provides a high-level overview of the paper, focusing on its objective, methods, results, and implications. Ensure your summary reflects the paper's content accurately, without adding interpretations or assumptions. Check your response for clarity, conciseness, and fidelity to the original text.>"
    content_cap: null
    param: {}